# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: datetime.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x64\x61tetime.proto\"\x1f\n\x0eResponseString\x12\r\n\x05value\x18\x01 \x01(\t\"\x1e\n\rRequestString\x12\r\n\x05value\x18\x01 \x01(\t2?\n\x0bGetDateTime\x12\x30\n\x0bSayDateTime\x12\x0e.RequestString\x1a\x0f.ResponseString\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'datetime_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_RESPONSESTRING']._serialized_start=18
  _globals['_RESPONSESTRING']._serialized_end=49
  _globals['_REQUESTSTRING']._serialized_start=51
  _globals['_REQUESTSTRING']._serialized_end=81
  _globals['_GETDATETIME']._serialized_start=83
  _globals['_GETDATETIME']._serialized_end=146
# @@protoc_insertion_point(module_scope)
