# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import datetime_pb2 as datetime__pb2


class GetDateTimeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SayDateTime = channel.unary_unary(
                '/GetDateTime/SayDateTime',
                request_serializer=datetime__pb2.RequestString.SerializeToString,
                response_deserializer=datetime__pb2.ResponseString.FromString,
                )


class GetDateTimeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SayDateTime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GetDateTimeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SayDateTime': grpc.unary_unary_rpc_method_handler(
                    servicer.SayDateTime,
                    request_deserializer=datetime__pb2.RequestString.FromString,
                    response_serializer=datetime__pb2.ResponseString.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'GetDateTime', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GetDateTime(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SayDateTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GetDateTime/SayDateTime',
            datetime__pb2.RequestString.SerializeToString,
            datetime__pb2.ResponseString.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
